# Generated by Django 5.2.7 on 2025-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac', models.CharField(help_text='MAC del ESP32 (AA:BB:CC:DD:EE:FF)', max_length=17, unique=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_on', models.BooleanField(default=False, help_text='Estado real reportado por el dispositivo')),
                ('desired_state', models.BooleanField(default=False, help_text='Comando deseado desde el servidor')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
